modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="smartzombies"
version="1.0.0"
displayName="Smart Zombies"
authors="Lkzin"
description='''
Makes zombies more survival-oriented: they can collect useful items,
use tools, break simple obstacles, build bridges/towers and pursue players.
'''

[[dependencies.smartzombies]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.smartzombies]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"